name: Build
on:
  push:
    branches:
      - master
jobs:
  build-jar-package:
    runs-on: macos-11
    steps:
      - name: Checkout
        uses: actions/checkout@v2.7.0
      - name: Setup Java JDK
        uses: actions/setup-java@v2.5.1
        with:
          java-version: '8'
          distribution: 'adopt-openj9'
          java-package: 'jdk'
          architecture: 'x64'
          check-latest: false
      - name: Build Client JAR
        working-directory: ./Client/src
        run: |
          mkdir ../target
          javac Launcher.java -d ../target
          cd ../target
          jar -cvfm ../FakeMB-Client-x64.jar ../META-INF/MENIFEST.MF *
      - name: Automatic Releases
        uses: marvinpinto/action-automatic-releases@v1.2.1
        with:
          repo_token: "${{ secrets.GITREPO_TOKEN }}"
          automatic_release_tag: 'auto-dev'
          draft: false
          prerelease: true
          title: 'Auto Development Release'
          files: |
            ./Client/FakeMB-Client-x64.jar
