name: Build
on: [push]
jobs:
  build-jar-package:
    runs-on: macos-11
    steps:
      - name: Checkout
        uses: actions/checkout@v2.7.0
      - name: Setup Java JDK
        uses: actions/setup-java@v2.5.1
        with:
          java-version: '8'
          distribution: 'adopt-openj9'
          java-package: 'jdk'
          architecture: 'x86'
          check-latest: false
      - name: Build Client JAR
        working-directory: ./Client
        run: |
          javac src/Launcher.java -d target
          jar -cvfm FakeMB-Client.jar META-INF/MENIFEST.MF *
      - name: Automatic Releases
        uses: marvinpinto/action-automatic-releases@v1.2.1
        with:
          repo_token: "${{ secrets.GITREPO_TOKEN }}"
          automatic_release_tag: 'auto-dev'
          draft: true
          prerelease: true
          title: 'Auto Development Release'
          files: |
            ./Client/FakeMB-Client.jar
      
